---
# Prevent players from dropping items from their inventory
# Copyright (C) 2020-2022 KygekDev
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# he Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

name: NoDropItem
author: KygekDev
version: 2.0.0
api: 4.0.0
main: KygekDev\NoDropItem\NoDropItem
description: Prevent players from dropping items from their inventory
website: https://github.com/kdpls/NoDropItem

permissions:
  nodropitem.bypass:
    description: Bypasses NoDropItem plugin check
    default: op
...
